amqp:
  username: "guest"
  password: "guest"
  host: "localhost:5672"
  vhost: ""

queues:
  # Local queues for receiving commands
  - name: "events"
    consumer: "events_consumer"
    remote: false

monitoring:
  enabled: true
  interval: "1s"

logging:
  agent:
    directory: "logs/agent"
    prefix: "agent"
    console: true
    file: true
    max_size: 100
    max_age: 7
    compress: true