amqp:
  username: "guest"
  password: "guest"
  host: "localhost:5672"
  vhost: ""
queues:
  - name: "Tester"
    consumer: "events_consumer"
monitoring:
  enabled: true
  interval: "1s"
logging:
  agent:
    directory: "logs/agent"
    prefix: "agent"
    console: true
    file: true
    max_size: 100
    max_age: 7
    compress: true
  producer:
    directory: "logs/producer"
    prefix: "producer"
    console: true
    file: true
    max_size: 50
    max_age: 3
    compress: true
  monitor:
    directory: "logs/monitor"
    prefix: "monitor"
    console: true
    file: true
    max_size: 50
    max_age: 3
    compress: true
  