amqp:
  username: "guest"
  password: "guest"
  host: "localhost:5672"
  vhost: ""

queues:
  # Local queues for receiving commands
  - name: "Tester"
    consumer: "events_consumer"
    remote: false
  
monitoring:
  enabled: true
  interval: "1s"

logging:
  monitor:
    directory: "logs/monitor"
    prefix: "monitor"
    console: true
    file: true
    max_size: 50
    max_age: 3
    compress: true
  